apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagpdevelopdemo-deployment
spec:
  selector:
    matchLabels:
      app: nagpdevelopdemo-pod
  replicas: 4
  template:
    metadata:
      labels:
        app: nagpdevelopdemo-pod
    spec:
      containers:
        - name: nagpdevelopdemo-container
          image: cloudvivek/i-vivekkumar04-develop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
    name: nagpdevelopdemo-service
spec:
    ports:
    - name: http
      port: 80
      targetPort: 80
    selector:
        app: nagpdevelopdemo-pod
    type: LoadBalancer

---

apiVersion: v1
kind: Secret
metadata:
  name: developsecret
type: Opaque
data:
  branch: ZGV2ZWxvcA==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: develop-configmap
data:
  branch: "develop"