apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagpmasterdemo-deployment
spec:
  selector:
    matchLabels:
      app: nagpmasterdemo-pod
  replicas: 4
  template:
    metadata:
      labels:
        app: nagpmasterdemo-pod
    spec:
      containers:
        - name: nagpmasterdemo-container
          image: cloudvivek/i-vivekkumar04-master:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7005
--- 
apiVersion: v1
kind: Service
metadata:
    name: nagpmasterdemo-service
spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80

    selector:
        app: nagpmasterdemo-pod
    type: LoadBalancer

---

apiVersion: v1
kind: Secret
metadata:
  name: mastersecret
type: Opaque
data:
  branch: bWFzdGVy

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: master-configmap
data:
  branch: "master"